export const GET_VIDEOS_SUCCESS = 'GET_VIDEOS_SUCCESS';
export const GET_VIDEOS_STARTED = 'GET_VIDEOS_STARTED';
export const GET_VIDEOS_FAILURE = 'GET_VIDEOS_FAILURE';

export const UPDATE_MAIN_SUCCESS = 'UPDATE_MAIN_SUCCESS';
export const UPDATE_MAIN_STARTED = 'UPDATE_MAIN_STARTED';
export const UPDATE_MAIN_FAILURE = 'UPDATE_MAIN_FAILURE';

export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_STARTED = 'ADD_COMMENT_STARTED';
export const ADD_COMMENT_FAILURE = 'ADD_COMMENT_FAILURE';

export const DELETE_COMMENT = 'DELETE_COMMENT';
