export const UPDATE_MAINVIDEO = 'UPDATE_MAINVIDEO';
export const GET_VIDEOS_SUCCESS = 'GET_VIDEOS_SUCCESS';
export const GET_VIDEOS_STARTED = 'GET_VIDEOS_STARTED';
export const GET_VIDEOS_FAILURE = 'GET_VIDEOS_FAILURE';
export const ADD_COMMENT = 'ADD_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';

export const UPDATE_MAIN_SUCCESS = 'UPDATE_MAIN_SUCCESS';
export const UPDATE_MAIN_STARTED = 'UPDATE_MAIN_STARTED';
export const UPDATE_MAIN_FAILURE = 'UPDATE_MAIN_FAILURE';

